export const SMARTCITY_OVERVIEW_REFRESH = "SMARTCITY_OVERVIEW_REFRESH"
export const SMARTCITY_REGION_FILTER = "SMARTCITY_REGION_FILTER"
export const SMARTCITY_LEGEND_FILTER = "SMARTCITY_LEGEND_FILTER"
